server:
    port: 8082
    servlet:
        context-path: /home-web

management:
    endpoint:
        shutdown:
            enabled: false
    endpoints:
        web:
            base-path: /config-actuator
            exposure:
                include: "*"

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

data:
    env: NaN
    user:
        name: NaN
        age: NaN

logging:
    level:
        org.springframework.web: TRACE
