server:
    port: 8080
    servlet:
        context-path: /home-web

management:
    endpoints:
        web:
            base-path: /config-actuator
            exposure:
                include: "*"

data:
    env: NaN
    user:
        name: NaN
        age: NaN

logging:
    level:
        org.springframework.web: TRACE

